In [1]:
import pandas as pd

In [4]:
students=pd.read_csv("StudentsPerformance.csv")
students

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

QN.1
How many female students scored 80 and above in mathematics?

In [5]:
len(students[(students["gender"] == "female") & (students["math score"] >= 80)])

74

QN.2 What is the mean reading score of students who completed the test preparation course

In [6]:
students[students["test preparation course"]=="completed"]["reading score"].mean()

np.float64(73.89385474860335)

QN.3 WHAT IS THE RANGE OF THE WRITING SCORE

In [7]:
students["writing score"].max()-students["writing score"].min()

np.int64(90)

QN.4 Find the standard deviation of the male students and their reading score

In [8]:
students[students["gender"]=="male"]["reading score"].std()

np.float64(13.931832063729495)

QN.5 Compute the total score that is to say math, reading, writing

In [11]:
students["total score"]=(
    students["math score"]+
    students["reading score"]+
    students["writing score"]
)
students.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total scor,total score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,218
1,female,group C,some college,standard,completed,69,90,88,247,247
2,female,group B,master's degree,standard,none,90,95,93,278,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,148
4,male,group C,some college,standard,none,76,78,75,229,229

a) Find the average of the total score

In [12]:
students["total score"].mean()

np.float64(203.312)

b) the 90th percentile of the total score

In [13]:
students["total score"].quantile(0.90)

np.float64(258.0)

c) find the inter quartile range

In [14]:
students["total score"].quantile(0.75)-students["total score"].quantile(0.25)

np.float64(58.0)